name: Generate docs

on:
  push:
    branches:
      - main
    paths:
      - Common/msal-node-wrapper/**
  pull_request:
    branches:
      - main
    paths:
      - Common/msal-node-wrapper/**

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Use Node.js
        uses: actions/setup-node@v1
        env:
          RUNNING_NODE_CI: 1
      - run: |
          cd Common/msal-node-wrapper
          npm ci
          npm run build
          npm run docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          destination_dir: ./docs
          keep_files: true